//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsRelation.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConceptsRelationDBEntities : DbContext
    {
        public ConceptsRelationDBEntities()
            : base("name=ConceptsRelationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MasterConceptRelation> MasterConceptRelations { get; set; }
        public virtual DbSet<Relation> Relations { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<ConceptOne> ConceptOnes { get; set; }
        public virtual DbSet<ConceptTwo> ConceptTwoes { get; set; }
        public virtual DbSet<SaveAllCR> SaveAllCRs { get; set; }
    }
}
