//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsRelation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptOne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConceptOne()
        {
            this.SaveAllCRs = new HashSet<SaveAllCR>();
        }
    
        public int C1Id { get; set; }
        public string ConceptOneName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaveAllCR> SaveAllCRs { get; set; }
    }
}
