//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsRelation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterConceptRelation
    {
        public int CrID { get; set; }
        public string TopicID { get; set; }
        public string ConceptOne { get; set; }
        public string ConceptTwo { get; set; }
        public string CoceptRelation { get; set; }
        public string TopicName { get; set; }
    }
}
