//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsRelation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveAllCR
    {
        public int Id { get; set; }
        public int fTopicId { get; set; }
        public int fRId { get; set; }
        public int fC1Id { get; set; }
        public int fC2Id { get; set; }
    
        public virtual ConceptOne ConceptOne { get; set; }
        public virtual ConceptTwo ConceptTwo { get; set; }
        public virtual Relation Relation { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
